# Generated by Django 4.2.7 on 2023-12-07 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount', models.PositiveIntegerField()),
                ('day', models.DateField(default=datetime.date.today)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='finance.asset')),
            ],
        ),
    ]
