# Generated by Django 4.2.7 on 2023-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='finance.asset'),
        ),
    ]
